name: Workflow to deploy ADF ARM Template to Prod
on: 
  push:
    branches: 
      master
    paths:
      - <path-to-adf-publish>/**

env:
  AZURE_RESOURCE_GROUP: adf_example_prod                        # set this to your Azure Resource group's name  
  AZURE_SUBSCRIPTION_ID: ${{ secrets.SP_SUBSCRIPTION_ID }}      # set this to your Azure Subscription Id
  AZURE_SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
  AZURE_DEV_DF_NAME: <>
  AZURE_PRD_DF_NAME: <>
  STORAGE_ACCOUNT_NAME: <>
  VAULT_NAME: ${{ secrets.AZURE_KV_NAME }}
  PROD_STORAGE_CONN: ${{ secrets.PROD_STORAGE_CONN }}

jobs:
  build-and-deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
       
    - uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: ${{ env.VAULT_NAME }}
        secrets: 'storageconn'
      id: myGetSecretAction
    
    
    #Deployment of ARM template    
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ${{ github.workspace }}/${{ env.AZURE_DEV_DF_NAME }}/ARMTemplateForFactory.json             
        parameters: ${{ github.workspace }}/${{ env.AZURE_DEV_DF_NAME }}/ARMTemplateParametersForFactory.json 
                    factoryName=${{ env.AZURE_PRD_DF_NAME }} 
                    adfbloblink01_connectionString=${{ env.PROD_STORAGE_CONN }} 
